# Site settings
author: Bertha Muteba
title: 
header-img: img/home-bg.png
email: nyc_bm26@aol.com
copyright_name: Bertha Muteba
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  C0d1NGBaDaZZ2391

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
